[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["fireants"]

[project]
name = "fireants"
version = "0.1.1"
authors = [
    {name="Rohit Jena"},
    {name="Pratik Chaudhari"},
    {name="James C. Gee"}
]
description = "FireANTs: Adaptive Riemannian Optimization for Multi-Scale Diffeomorphic Registration"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "torch==1.13.1",
    "SimpleITK==2.2.1", 
    "nibabel==4.0.2",
    "numpy", "scipy", "scikit-image", "matplotlib",
    "typing", "tqdm", "pandas==1.3.5", "nibabel==4.0.2",
]