debug: True
verbose: True

# input params
image_file: oasis_subjects.txt
image_prefix: /mnt/rohit_data2/neurite-OASIS/
image_suffix: /aligned_norm.nii.gz
num_subjects: 16    # set to null to use all subjects

# template params
init_template_path: /mnt/rohit_data2/neurite-OASIS/OASIS_OAS1_0270_MR1/aligned_norm.nii.gz
# init_template_path: null
template_iterations: 6

# laplacian params
num_laplacian: 2
laplace_params:
  learning_rate: 0.5
  itk_scale: true

# save outputs
save_dir: ./saved_templates
save_every: 1               # number of epochs to save the template (last epoch will always be saved)
save_init_template: True  
save_moved_images: False    # set to true if you want to save the moved images at last step (used for template creation)
# no num_subjects: will be the same as the number of subjects used for creation
save_additional:
  image_file: []
  image_prefix: []
  image_suffix: []
  is_segmentation: []

# registration params
batch_size: 10

# rigid transform
do_rigid: False
rigid:
  iterations: [200, 100, 25]
  scales: [4, 2, 1]
  progress_bar: ${verbose}
  loss_type: cc

# affine transform
do_affine: False
affine:
  iterations: [200, 100, 25]
  scales: [4, 2, 1]
  progress_bar: ${verbose}
  loss_type: cc

# deformation transform
do_deform: True
deform_algo: greedy
deform:
  iterations: [200, 100, 50]
  scales: [4, 2, 1]
  optimizer_lr: 0.25        # for template creation, use lower learning rate than pairwise
  smooth_warp_sigma: 0.5
  smooth_grad_sigma: 1.0
  progress_bar: ${verbose}
  cc_kernel_size: 5

# additional params
tmpdir: null
last_reg: null
